name: CI/CD

on: [push, workflow_dispatch]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: FedericoCarboni/setup-ffmpeg@v1
        id: setup-ffmpeg

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Create bundle
        run: pyinstaller cd.spec

      - run: |
          cd dist
          dir

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: ${{ github.workspace }}\dist\*.exe
          retention-days: 90


  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo sed -i '' 's|C:/hostedtoolcache/windows|/Users/runner/hostedtoolcache|' cd.spec
          sudo sed -i '' 's|.exe||' cd.spec
          python -m pip install -r requirements.txt

      - uses: FedericoCarboni/setup-ffmpeg@v1
        id: setup-ffmpeg

      - run: |
          echo $PATH
          cd /Users/runner/hostedtoolcache/ffmpeg/5.0.1/x64/
          ls

      - name: Create bundle
        run: pyinstaller cd.spec

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: ${{ github.workspace }}/dist/*
          retention-days: 90