name: CI/CD

on: [push, workflow_dispatch]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: FedericoCarboni/setup-ffmpeg@v1
        id: setup-ffmpeg

      - uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Create bundle
        run: |
          (gc karaluxer.spec) -replace 'tools/ffmpeg.exe', 'C:/hostedtoolcache/windows/ffmpeg/5.0.1/x64/ffmpeg.exe' | Out-File -encoding UTF8 karaluxer.spec
          (gc karaluxer.spec) -replace 'venv/', 'C:/hostedtoolcache/windows/Python/3.10.8/x64/' | Out-File -encoding UTF8 karaluxer.spec
          pyinstaller karaluxer.spec

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: ${{ github.workspace }}\dist\*.exe
          retention-days: 90


  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install ffmpeg
        run: brew install ffmpeg

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo sed -i '' 's|tools/ffmpeg.exe|/usr/local/Cellar/ffmpeg/5.1.2/bin/ffmpeg|' karaluxer.spec
          sudo sed -i '' 's|venv/lib/|/Users/runner/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/|' karaluxer.spec
          python -m pip install -r requirements.txt

      - name: Create bundle
        run: pyinstaller karaluxer.spec

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macos
          path: ${{ github.workspace }}/dist/*
          retention-days: 90

  ubuntu:
    runs-on:   ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg python3-pyqt5

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo sed -i 's|tools/ffmpeg.exe|/usr/bin/ffmpeg|' karaluxer.spec
          sudo sed -i 's|venv/lib/|/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/|' karaluxer.spec
          python -m pip install -r requirements.txt

      - name: Create bundle
        run: pyinstaller karaluxer.spec

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu
          path: ${{ github.workspace }}/dist/*
          retention-days: 90