name: CI/CD

on: [push, workflow_dispatch]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: FedericoCarboni/setup-ffmpeg@v1
        id: setup-ffmpeg

      - uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Create bundle
        run: pyinstaller cd.spec

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: ${{ github.workspace }}\dist\*.exe
          retention-days: 90


  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install ffmpeg
        run: brew install ffmpeg

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo sed -i '' 's|C:/hostedtoolcache/windows/ffmpeg/5.0.1/x64/ffmpeg.exe|/usr/local/Cellar/ffmpeg/5.1.2/bin/ffmpeg|' cd.spec
          sudo sed -i '' 's|C:/hostedtoolcache/windows/Python/3.10.8/x64/lib/site-packages/certifi/cacert.pem|/Users/runner/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/certifi/cacert.pem|' cd.spec
          python -m pip install -r requirements.txt

      - name: Create bundle
        run: pyinstaller cd.spec

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macos
          path: ${{ github.workspace }}/dist/*
          retention-days: 90